import { Client } from "./types";

// クライアントマスタ（将来的にDB接続に差し替え可能）
// chatworkRoomId: ChatworkのルームID（未設定の場合は送信ボタンが非表示になる）
export const CLIENTS: Client[] = [
  { id: "kobayashi-kenzai", name: "小林建材", chatworkRoomId: "YOUR_ROOM_ID_1" },
  { id: "kanagawa-gangu", name: "神奈川玩具", chatworkRoomId: "YOUR_ROOM_ID_2" },
  { id: "fusousha", name: "扶桑社", chatworkRoomId: "YOUR_ROOM_ID_3" },
  { id: "ashigara-kanko", name: "足柄観光バス", chatworkRoomId: "YOUR_ROOM_ID_4" },
  { id: "client-05", name: "サンプル商事05" },
  { id: "client-06", name: "サンプル商事06" },
  { id: "client-07", name: "サンプル商事07" },
  { id: "client-08", name: "サンプル商事08" },
  { id: "client-09", name: "サンプル商事09" },
  { id: "client-10", name: "サンプル商事10" },
  { id: "client-11", name: "サンプル商事11" },
  { id: "client-12", name: "サンプル商事12" },
  { id: "client-13", name: "サンプル商事13" },
  { id: "client-14", name: "サンプル商事14" },
  { id: "client-15", name: "サンプル商事15" },
  { id: "client-16", name: "サンプル商事16" },
  { id: "client-17", name: "サンプル商事17" },
  { id: "client-18", name: "サンプル商事18" },
  { id: "client-19", name: "サンプル商事19" },
  { id: "client-20", name: "サンプル商事20" },
  { id: "client-21", name: "サンプル商事21" },
  { id: "client-22", name: "サンプル商事22" },
  { id: "client-23", name: "サンプル商事23" },
  { id: "client-24", name: "サンプル商事24" },
  { id: "client-25", name: "サンプル商事25" },
  { id: "client-26", name: "サンプル商事26" },
  { id: "client-27", name: "サンプル商事27" },
  { id: "client-28", name: "サンプル商事28" },
  { id: "client-29", name: "サンプル商事29" },
  { id: "client-30", name: "サンプル商事30" },
  { id: "client-31", name: "サンプル商事31" },
  { id: "client-32", name: "サンプル商事32" },
  { id: "client-33", name: "サンプル商事33" },
];
